add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$time\
$status\
$character"""

[battery]
disabled = true

[directory]
truncation_length = 16
truncation_symbol = "…/"

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[status]
disabled = false
symbol = "✖ "

[time]
disabled = false